### ISSUE TITLE
Handling (de)serialization modes for 64-bit integer types

### ISSUE THREAD

**Issue by scvnc** [agreatfool/grpc_tools_node_protoc_ts#10]
If I add the `[jstype=JS_STRING]` option to a message then the generated stubs will return a string for the 64-bit integer value.  The generated typescript definition does not handle this.  I'll let you know if I attempt a pull request to add this functionality but for now I am overriding the typescript guards in my code for now.

## Example
```
message Book {
    int64 isbn = 1 [jstype=JS_STRING];
    string title = 2;
    string author = 3;
}
```
Note that the generated code has a `readInt64String()` invocation that works as expected.  The value of the message is of type `string` instead of `number`.  
```
proto.core.Book.deserializeBinaryFromReader = function(msg, reader) {

  // ... 
  var value = /** @type {string} */ (reader.readInt64String());
  msg.setTarget(value)

}
```

## Background

https://github.com/google/protobuf/issues/3666

When taking the static stub generation google/protobuf has an [obscure configuration][1] that will (de)serialize 64-bit integers into strings. I am satisfied with parsing this with some other module that can manipulate the long number at this point. 

[0]: https://github.com/dcodeIO/protobuf.js
[1]: https://github.com/google/protobuf/pull/1832

**Comment by agreatfool** [comment]
Thank you for your issue. This surely is the issue shall be fixed.
And these days I found 3rd lib [protobuf.js](https://github.com/dcodeIO/protobuf.js) already has the functionality to handle gRPC js code generation & d.ts definition. You can have a look.
From version [6.8.0](https://github.com/dcodeIO/protobuf.js/blob/master/CHANGELOG.md#680).

**Comment by scvnc** [comment]
Thanks for making this nice tool.

Yeah, [protobuf.js][0] seems to be used by grpc-node when dynamically generating the code at runtime.  It does handle serialization into Long.js which is very nice.  Since we want TypeScript support: having the code statically generated with typedefs makes sense. I don't have a clear recipe for combining [protobuf.js][0] with statically generated client stubs/messages but would be interested to know if you have accomplished that.

[0]: https://github.com/dcodeIO/protobuf.js

**Comment by agreatfool** [comment]
I just found in the doc of version 6.8.4, protobuf.js provided the functionality to generate static code files.

Please check here: [Command Line > pbjs for JavaScript](https://github.com/dcodeIO/ProtoBuf.js/#pbjs-for-javascript)
> $> pbjs -t static-module -w commonjs -o compiled.js file1.proto file2.proto
    will generate static code for definitions within `file1.proto` and `file2.proto` to a CommonJS module `compiled.js`.

And also: [Command Line > pbts for TypeScript](https://github.com/dcodeIO/ProtoBuf.js/#pbts-for-typescript)
> $> pbts -o compiled.d.ts compiled.js

I just made some test yesterday, seems it works very good. Maybe you can have a try.

The tool used to generate javascript code from protobuf which provided by [google official](https://www.npmjs.com/package/grpc-tools), just, how to say, "javascript version too old". Which just not following the latest javascript grammar & javascript development trends.

So I think maybe protobuf.js is a better choice for the users who want static code generation, just like you and me.

**Comment by agreatfool** [comment]
One more issue have to be fixed before using protobuf.js as  a grpc static code generator.

Since protobuf.js is a tool `protobuf` oriented, not `grpc` oriented. So it provides the option which rpc tool you want to use. That means the code generated with protobuf.js has no rpc implementation. Not like `grpc-tools`, that tool would generate code with gRPC official implementation.

See [Examples > Using services](https://github.com/dcodeIO/ProtoBuf.js/#using-services) and [examples/streaming-rpc.js](https://github.com/dcodeIO/protobuf.js/blob/master/examples/streaming-rpc.js).

And I searched around, seems no official or 3rd tutorial how to combine protobuf.js with gRPC. It may cost a lot of time to solve this issue.

**Comment by scvnc** [comment]
Good to resonate on that clarity. Even if protobuf.js does not handle the grpc service implementation it may be worthwhile.  Later, perhaps there could be some way to decouple the grpc service generation from this project.
