### ISSUE TITLE
How to build once for protos in multiple folders?

### ISSUE THREAD

**Issue by alienzhangyw** [agreatfool/grpc_tools_node_protoc_ts#106]
For example, sub folders in the proto folder:
proto/
  |--auth
  |--data
  |--config
There’re some .proto files in each folder。

I tried 
```
grpc_tools_node_protoc \
--js_out=import_style=commonjs,binary:./your_dest_dir \
--grpc_out=./your_dest_dir \
--plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` \
-I ./proto \
./proto/*/*.proto
````
but got Error: Invalid file name pattern or missing input file

**Comment by agreatfool** [comment]
I just tested, seems all good. I guess you execute the command at the wrong place. Pay attention to `./proto....`.

![image](https://user-images.githubusercontent.com/195293/122173506-5fb40300-ceb4-11eb-87cb-c5c7b8c7187c.png)

![image](https://user-images.githubusercontent.com/195293/122173536-66db1100-ceb4-11eb-9107-abfe100cc2ef.png)

**Comment by alienzhangyw** [comment]
> I just tested, seems all good. I guess you execute the command at the wrong place. Pay attention to `./proto....`.
> 
> ![image](https://user-images.githubusercontent.com/195293/122173506-5fb40300-ceb4-11eb-87cb-c5c7b8c7187c.png)
> 
> ![image](https://user-images.githubusercontent.com/195293/122173536-66db1100-ceb4-11eb-9107-abfe100cc2ef.png)

What does '-I' mean?
Can I use relative path in these commands? because my proto files are from another project.

**Comment by agreatfool** [comment]
Have a look at https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools. And since your question is related to node official tool. I'd suggest you raise an issue there.

**Comment by alienzhangyw** [comment]
This may be a Windows problem.
