### ISSUE TITLE
help with make a props read for nestjs framework

### ISSUE THREAD

**Issue by godtoy** [agreatfool/grpc_tools_node_protoc_ts#112]
it's the best tool to gen typescript for project but it's maybe miss some props read like this `https://www.npmjs.com/package/protoc-gen-ts` 

https://www.npmjs.com/package/protoc-gen-ts this lib is gen only interface api to read props like object, when im using nestjs  DI feature  like this 
![image](https://user-images.githubusercontent.com/13638996/128824334-9333a443-8a7f-4835-967b-1544383c7339.png)
it will not inject the LoginRequest object and therefore lacks the get set

**Comment by godtoy** [comment]
hope there is one way to convert a interface object to pb object

**Comment by godtoy** [comment]
or there is one way direct  to access props instead of get set method

**Comment by agreatfool** [comment]
Sorry, I didn't get the point. What feature actually you want?

One thing to mention is this repo is aiming to generate `d.ts` for the js codes generated by [grpc_tools_node_protoc](https://www.npmjs.com/package/grpc-tools). So for the `feature`s you want, you may need to raise ticket here: https://github.com/grpc/grpc-node.

**Comment by godtoy** [comment]
> Sorry, I didn't get the point. What feature actually you want? I'm not familiar with the DI feature of nestjs, a bit confused.
> 
> I guess you want
> 
> ```ts
> messageObject.someAttr
> ```
> 
> and now the coding style is
> 
> ```ts
> messageObject.getSomeAttr()
> ```
> 
> Am I correct?
> 
> One thing to mention is this repo is aiming to generate `d.ts` for the js codes generated by [grpc_tools_node_protoc](https://www.npmjs.com/package/grpc-tools). So for the `feature`s you want, you may need to raise ticket here: https://github.com/grpc/grpc-node.

Yes i want this like what you say. thanks.  i got it, i will publish a issue to `grpc_tools_node_protoc`
