### ISSUE TITLE
Inconsistency between `grpc_pb.js` and `grpc_pb.d.ts`

### ISSUE THREAD

**Issue by rubens21** [agreatfool/grpc_tools_node_protoc_ts#123]
Hi guys,

I am using the latest release (5.3.2), and running the command below:

```sh
grpc_tools_node_protoc \
      --plugin=protoc-gen-ts=/bin/grpc_tools_node_protoc \
      --grpc_out=grpc_js:output/js \
      --ts_out=output/js \
      --js_out=import_style=commonjs,binary:output/js  \
      -I/base/src file1.proto file2.proto
```

While the `...grpc_pb.js` file is correctly requiring `@grpc/grpc-js`, the `...grpc_pb.d.ts` file is importing `grpc`.

It is creating some issues in my environment (although I think it should not create problems :thinking: )

**Comment by rubens21** [comment]
Sorry guys, 

I was lead to this error because a small issue in the read me file.

When I was investigating to issue to trying to fix it, I figured out that the Readme file was slightly out of date.

I opened a PR to fix it.

https://github.com/agreatfool/grpc_tools_node_protoc_ts/pull/124

**Comment by rubens21** [comment]
for who came here with the same problem, the solution is using the option `grpc_js` in `ts_out` lag as I was using in `grpc_out` flag:

```
grpc_tools_node_protoc \
      --plugin=protoc-gen-ts=/bin/grpc_tools_node_protoc \
      --grpc_out=grpc_js:output/js \
      --ts_out=grpc_js:output/js \
      --js_out=import_style=commonjs,binary:output/js  \
      -I/base/src file1.proto file2.proto
```

**Comment by agreatfool** [comment]
Yep, the example part in README doc haven't been updated after `grpc_js` introduced. 

Thanks a lot. 

BTW, you could have a look at the examples dir: https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/v5.3.2/examples/bash/build.sh
