### ISSUE TITLE
Should TSLint just be disabled for generated files?

### ISSUE THREAD

**Issue by jcloutz** [agreatfool/grpc_tools_node_protoc_ts#13]
Would it make sense to just disable to TSLint for the generated files? It doesn't effect functionality of the generated files, but it is annoying having the errors constantly pop up. It can also cause issues if TSLint is part of a CI process of pre-commit hook.

```
/* tslint:disable */
```

**Comment by agreatfool** [comment]
Sure. 

I would check tomorrow if I could add some param in plugin execution. It's better to give the choice to users.

Like:

```bash
protoc \
--plugin=protoc-gen-ts=./bin/protoc-gen-ts \
--ts_out=no_lint=yes:${PROTO_DEST} \
-I ./proto \
proto/*.proto
```

And could you please give me some more information about the TSLint issues. Like the reproducing process.

**Comment by jcloutz** [comment]
Having more options is never bad. Maybe add an option for disabling it for the entire file, or pass a list of rules to disable? `/* tslint:disable:rule1 rule2 rule3... */`

Examples of the errors:
- `max-classes-per-file`: unavoidable
- `member-access`: Message objects have no member access modifiers 
- `member ordering`: static members come after non-static members and methods in generated messages
- `interface-over-type-literal`: `AsObject` is a type instead of an interface, and it doesn't start with `I` if it was an interface

Non of the effects the fact that it just works though, it's really just aesthetics and personal code style preferences.

I'm just not sure I see the need to have linting in generated files, it either works or it doesn't. Some changes could be made to make them pass the default tslint rules for the most part, except for the multiple classes rule which can't be avoided. However, if someone is using a modified tslint config it may throw different errors. 

If you want I can create a pull request to change the generated output so that it will pass the of the default tslint rules.

**Comment by agreatfool** [comment]
Finally I just disabled TSLint just like you mentioned at the beginning. New version released just now: [v2.1.2](https://www.npmjs.com/package/grpc_tools_node_protoc_ts).

Since I thought through again. Codes really running are the generated ones, from grpc-tools. And what current tool do is just add some definition for typescript. 

So whatever we do it's just meaningless. Our goal is to make tsc understand the generated js codes, and it's already done. That's OK.

What do you think?

**Comment by jcloutz** [comment]
That make sense to me, there is no reason to lint something that shouldn't be changed :)

**Comment by agreatfool** [comment]
That's cool. Thank you for your issue & PR. :)
