### ISSUE TITLE
Unable to catch error in try / catch

### ISSUE THREAD

**Issue by jambudipa** [agreatfool/grpc_tools_node_protoc_ts#134]
The following code is throwing an error:
```
const client = new ChatServiceClient('localhost:8080', grpc.credentials.createInsecure());
const question = new Question(input);
const responseStream = client.AskQuestion(question, meta);
```
Now this service is unavailable, but wrapping this code block in try / catch seemingly has no effect. Why might that be?

I cannot see any way to handle this connection error and my node app just stops...
>Error: 14 UNAVAILABLE: No connection established. Last error: connect ECONNREFUSED 127.0.0.1:8080 (2023-10-19T20:59:35.951Z)

**Comment by agreatfool** [comment]
@jambudipa You need to raise question to https://github.com/grpc/grpc-node/issues, this is the question about grpc itself, not about the typescript signature.

**Comment by jambudipa** [comment]
Aha ok, thanks, I’ll do that.
