### ISSUE TITLE
Importing from "Wrong" Module

### ISSUE THREAD

**Issue by the-nis-123** [agreatfool/grpc_tools_node_protoc_ts#135]
The typescript autogenerated  type definition fiile "_grpc.d.ts" file still imports from deprecated module"grpc" instead of "@grpc/grpc-js"

**Comment by agreatfool** [comment]
Please refer to:
- https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/master/examples/build/grpcjs/proto/book_grpc_pb.d.ts#L7
- https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/master/examples/bash/build.sh#L24-L43
