### ISSUE TITLE
Multiple services with similar methods

### ISSUE THREAD

**Issue by rensdewolf** [agreatfool/grpc_tools_node_protoc_ts#19]
If I define two services in the same proto file with similar method names but different parameters, the resulting definitions lead to conflicts. For example:

```
service Library {
    rpc GetBook (GetBookRequest) returns (Book) {}
}

service BookStore {
    rpc GetBook (GetBookOrder) returns (Book) {}
}
```

This creates two interfaces for GetBook (`IGetBook`) that have different implementations and lead to issues when using the typescript compiler. I wondered if there is a way to deal with this (within the same package scope)?

**Comment by agreatfool** [comment]
Fixed. Please check the latest version v2.2.4.

If any issues remained, please contact me again. Thanks for your issue.
