### ISSUE TITLE
Great tool

### ISSUE THREAD

**Issue by bcronje** [agreatfool/grpc_tools_node_protoc_ts#27]
After spending quite some time to try and find a TypeScript generator for code generated by grpc_tools_node_protoc I finally found this projects. So far it works great, so just wanted to say thank you.

Apologies for creating an Issue for this, but had no other way to say thank you.

**Comment by bcronje** [comment]
Thanks!

**Comment by agreatfool** [comment]
Thank u buddy. Comments like this just make me so happy.
