### ISSUE TITLE
Feature request: Generate an index.js & index.d.ts file so imports can come from one package

### ISSUE THREAD

**Issue by zakhenry** [agreatfool/grpc_tools_node_protoc_ts#29]
First off, thanks for creating such a great package! I've gone through a whole bunch of duds that only partially work with grpc eventually coming across this one that is so far so good :)

One question though - I want to be able to create an npm package that has my static definitions so that I can so something like the following
```ts
import { BookServiceClient } from '@mycompanyname/grpc';
```
rather than having to know the path structure of where the generated files are. Rather if I had a generated index.d.ts & index.js files, then I can have the `"main"` & `"typings"` entries in the `package.json` point to those files directly.

Is this possible? I might dig into the code a bit and see if I can raise a PR

**Comment by agreatfool** [comment]
Hi, sorry for the late reply.

As far as I know, the best solution of your issue is using relative file path. And make some command line bash script to do the compiling work.

Since you can control your js output files via `--js_out=import_style=commonjs,binary:./your_dest_dir --grpc_out=./your_dest_dir`, and also you can control the typescript output via `--ts_out=./your_dest_dir`. It's very simple to accomplish that script.

**Comment by zakhenry** [comment]
@agreatfool hmm I'm not sure that solves the issue as that is what I am currently doing. Basically what I'm after is a [typescript "barrel"](https://basarat.gitbooks.io/typescript/docs/tips/barrel.html) that exports all of the symbols from the generated code.

**Comment by zakhenry** [comment]
@agreatfool it's a bit hard to explain, so I've raised #31 which fixes this issue :)

**Comment by agreatfool** [comment]
@zakhenry The initial purpose of this project is generating the typescript definition according to the codes generated by `grpc_tools_node_protoc`. So this plugin is designed as simple as possible to make it flexible and easy to understand & use. There is no aggregation no sub directory, nothing more than definition files according to js files generated from `grpc_tools_node_protoc`.

I think it's better to do works which you described in some bash script or some wrapper project or framework etc. Leave this plugin as simple as possible, makes it easy to maintain & use.

What do you think :)
