### ISSUE TITLE
Why does this package depend on grpc?

### ISSUE THREAD

**Issue by murgatroid99** [agreatfool/grpc_tools_node_protoc_ts#40]
With `grpc-tools`, the expected usage pattern is that the generated code will live in the user's package, which will directly depend on `grpc` and `google-protobuf`. The README of this package seems to say that it is just doing additional typescript code generation on top of what `grpc-tools` generates. Is the expected usage pattern the same, or is there some reason I'm missing that this package depends on `grpc` directly?

**Comment by agreatfool** [comment]
Yes, you are correct. I just check the codes, there is no need to add the grpc in the dependency. I just removed it. Latest version 2.5.1 released.

Thank you for the notification.
