### ISSUE TITLE
Can I generate Web Client stub with this tool?

### ISSUE THREAD

**Issue by prabak** [agreatfool/grpc_tools_node_protoc_ts#42]
Hi,

I want to use Typescript with google's implementation of grpc-web. I am wondering can I use this tool to generate the web client stub with Typescript instead of Javascript? The following is what is used in google's implementation of grpc-web but it generates the Javascript stub for the web client

```protoc -I=$DIR echo.proto --js_out=import_style=commonjs:$OUT_DIR --grpc-web_out=import_style=commonjs,mode=grpcwebtext:$OUT_DIR```

thank you
Prabakar

**Comment by agreatfool** [comment]
Hi,

I haven't use grpc-web before. So currently I can hardly tell you can or can't. 

The purpose of this project is to generate the `typescript signature` of the `codes generated` from `grpc_tools_node_protoc `. So if it's still used in grpc-web, and you want the typescript signature for those generated codes, I think you can use this tool as usual.

Best Regards,
Jonathan
