### ISSUE TITLE
Service type definitions not generated

### ISSUE THREAD

**Issue by you-fail-me** [agreatfool/grpc_tools_node_protoc_ts#44]
When I run the script, as described in the readme:
```
protoc \
--plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
--ts_out=./generated \
-I ./protos \
./protos/*.proto
```
I get only `*_pb.d.ts` generated, no `*_grpc_pb.d.ts`, which means there's no type defs for the service and its methods.

What am I doing wrong here, how do I get that?

Also, seems like the code in the example dir is very unobvious and would benefit from better docs and explanations:
* what does the `protoc-gen-ts` file in the root `bin` directory do? Looks like some workaround, but no comment and no docs;
* what are the contents of the `build` root dir?

The way you generate code in examples is different from what you describe in the readme (namely the `--plugin=protoc-gen-ts` part for TS), would be nice to get that explained so I can actually use the tool

**Comment by agreatfool** [comment]
1. You could paste your `*.proto` file here, then I could have a look.

2. `protoc-gen-ts` is a plugin for `protoc` command, see: [Create a plugin for Google Protocol Buffer](https://www.expobrain.net/2015/09/13/create-a-plugin-for-google-protocol-buffer/).

3. `build` dir contains all js codes compiled from typescript source code, see: [tsconfig.json](https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/master/tsconfig.json).

```
"outDir": "build",
```

4. Difference between README & example:

README: 
```
# generate d.ts codes
protoc \
--plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
--ts_out=./your_dest_dir \
-I ./proto \
./your_proto_dir/*.proto
```

example:
```
grpc_tools_node_protoc \
--plugin=protoc-gen-ts=../bin/protoc-gen-ts \
--ts_out=${PROTO_DEST} \
-I ./proto \
proto/*.proto
```

Only difference is `protoc` & `grpc_tools_node_protoc`, as the functionality of them are almost same. `grpc_tools_node_protoc` is a wrapper of `protoc`. So it's ok to work.

**Comment by you-fail-me** [comment]
Thanks. So the build is just the output of tsc right?

My .proto:
```
syntax = "proto3"; //Specify proto3 version.
 
package test;
 
service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}
```

**Comment by agreatfool** [comment]
Yes, js codes from `tsc` command.

---

Test with steps:

1. Delete file: `examples/proto/book.proto`.
2. Delete all `examples/src/*`.
3. Delete all `examples/build/*`.
4. Create file: `examples/proto/test.proto`.
5. Paste your codes into it.
6. Run `examples/bash/build.sh`.
7. See generated: `examples/src/proto/*`.

There is file you want: `examples/src/proto/test_grpc_pb.d.ts`

```typescript
// package: test
// file: test.proto

/* tslint:disable */

import * as grpc from "grpc";
import * as test_pb from "./test_pb";

interface IGreeterService extends grpc.ServiceDefinition<grpc.UntypedServiceImplementation> {
    sayHello: IGreeterService_ISayHello;
}

interface IGreeterService_ISayHello extends grpc.MethodDefinition<test_pb.HelloRequest, test_pb.HelloReply> {
    path: string; // "/test.Greeter/SayHello"
    requestStream: boolean; // false
    responseStream: boolean; // false
    requestSerialize: grpc.serialize<test_pb.HelloRequest>;
    requestDeserialize: grpc.deserialize<test_pb.HelloRequest>;
    responseSerialize: grpc.serialize<test_pb.HelloReply>;
    responseDeserialize: grpc.deserialize<test_pb.HelloReply>;
}

export const GreeterService: IGreeterService;

export interface IGreeterServer {
    sayHello: grpc.handleUnaryCall<test_pb.HelloRequest, test_pb.HelloReply>;
}

export interface IGreeterClient {
    sayHello(request: test_pb.HelloRequest, callback: (error: grpc.ServiceError | null, response: test_pb.HelloReply) => void): grpc.ClientUnaryCall;
    sayHello(request: test_pb.HelloRequest, metadata: grpc.Metadata, callback: (error: grpc.ServiceError | null, response: test_pb.HelloReply) => void): grpc.ClientUnaryCall;
    sayHello(request: test_pb.HelloRequest, metadata: grpc.Metadata, options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: test_pb.HelloReply) => void): grpc.ClientUnaryCall;
}

export class GreeterClient extends grpc.Client implements IGreeterClient {
    constructor(address: string, credentials: grpc.ChannelCredentials, options?: object);
    public sayHello(request: test_pb.HelloRequest, callback: (error: grpc.ServiceError | null, response: test_pb.HelloReply) => void): grpc.ClientUnaryCall;
    public sayHello(request: test_pb.HelloRequest, metadata: grpc.Metadata, callback: (error: grpc.ServiceError | null, response: test_pb.HelloReply) => void): grpc.ClientUnaryCall;
    public sayHello(request: test_pb.HelloRequest, metadata: grpc.Metadata, options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: test_pb.HelloReply) => void): grpc.ClientUnaryCall;
}
```

**Comment by agreatfool** [comment]
You could have a try by yourself. At least the functionality is all ok. As I just tested.

Maybe you could double check your `protoc` command.

**Comment by you-fail-me** [comment]
For anyone else who might stumble upon this: turns out things really work, it looks like I had a dependency installed, which for some reason caused the issue I was experiencing. I had `ts-protoc-gen` installed to the project, and for some weird reason after I've removed it from package.json and did a fresh install of dependencies things started working.

thanks @agreatfool for checking and quick responses!

**Comment by agreatfool** [comment]
Welcomed 👍
