### ISSUE TITLE
Proto2 scalar field getters should not return undefined

### ISSUE THREAD

**Issue by martinxsliu** [agreatfool/grpc_tools_node_protoc_ts#45]
Currently, the generated getter methods for scalar fields will sometimes include undefined, e.g. `getFoo(): string | undefined;`

However, according to the [docs](https://developers.google.com/protocol-buffers/docs/reference/javascript-generated#singular-scalar-proto2) and my own experimentation, the getter methods for proto2 messages do not ever return undefined, and will always return the default value if the field is unset. For scalar fields, the default value is the zero value (e.g. `0`, `''`, etc), for repeated fields it is empty array, and for message fields it is undefined.

**Comment by agreatfool** [comment]
Could you please provide a reproducible proto file or sample codes.

**Comment by martinxsliu** [comment]
@agreatfool See gist: https://gist.github.com/martinxsliu/ee6d3ef08ce02e6d26046706842e5ff3

The node console output shows that scalar getters always return the default value of the scalar type, and will only return `undefined` for an optional message field. This is consistent with what the documentation states: https://developers.google.com/protocol-buffers/docs/proto#optional.

Also, the generated type for a bytes field _are_ correct. Namely that the getter is typed as `Uint8Array | string`, and the `_asU8` and `_asB64` methods do not have undefineds.

The `AsObject` types also look correct, as all the optional protobuf fields except for the bytes field are typed as optional. This is consistent with what I saw in the node console.

**Comment by agreatfool** [comment]
Hi martin,

I just realized you are talking about protobuf version 2.

It's recommended to use protobuf version 3 while using gRPC. See official doc: [here](https://grpc.io/docs/guides/#protocol-buffer-versions).

> In general, while you can use proto2 (the current default protocol buffers version), we recommend that you use proto3 with gRPC as it lets you use the full range of gRPC-supported languages ...

So there is no plan to be compatible with version 2.

Thanks.

**Comment by agreatfool** [comment]
I would close this issue a bit later. If you think there is still some optimization shall be done, just comment here.
