### ISSUE TITLE
How to get latest release?  (latest published version is 2.3.0)

### ISSUE THREAD

**Issue by clehene** [agreatfool/grpc_tools_node_protoc_ts#50]
What's the recommended way to use / upgrade this? 
The README suggests npm registry but I can only see 2.3.0 there https://www.npmjs.com/package/grpc-tools-ts

**Comment by agreatfool** [comment]
Hi,

Link you provided is not published by me. Correct npm packaged published & maintained by me is https://www.npmjs.com/package/grpc_tools_node_protoc_ts.

Just have a look.

Best Regards
