### ISSUE TITLE
High severity vulnerability in 'handlebars' dependency.

### ISSUE THREAD

**Issue by zFadil995** [agreatfool/grpc_tools_node_protoc_ts#52]
npm reports **2 high severity** vulnerabilities when installing the latest version that is available; both in handlebars 4.5.2, one that allows for Arbitrary Code Execution. 

Could the dependency be updated to the latest version (4.5.3 at the time of writing)? Or should I fork the repo and make a pull request if you are unable to get to it yourself?

**Comment by agreatfool** [comment]
Thank you for the report. Version 2.5.9 has just been released.
