### ISSUE TITLE
Add support for generate_package_definition

### ISSUE THREAD

**Issue by smnbbrv** [agreatfool/grpc_tools_node_protoc_ts#56]
Hi @agreatfool 

thank you for your work! The tool is very much helpful.

There is a quite new feature flag [generate_package_definition](https://github.com/grpc/grpc-node/issues/931) on the `gprc-tools`'s `protoc` that is missing in your implementation.

It does not rely on `grpc` package anymore and that's why it breaks the generated definitions for the client.

In fact, the very first I need to do after running your plugin is changing 

```ts
- import * as grpc from "grpc";
+ import * as grpc from "@grpc/grpc-js";
```

The next difference is the exported token that is not exported in a way it was before, but it uses the full path

```ts
var PdfGeneratorServiceService = exports['services.pdf.PdfGeneratorService'] = {
  //...
```

So it is not accessible anymore through the simple import

```ts
import {PdfGeneratorServiceService} from '...';
```

The full package path is required.

Actually, after this is implemented one can use your tool with `@grpc/grpc-js` as well as with `grpc`.

**Comment by agreatfool** [comment]
Gotcha, let me have a look.

**Comment by agreatfool** [comment]
Hi @smnbbrv ,

I just walked through the issue u mentioned. And just reproduced the exactly same error: https://github.com/grpc/grpc-node/issues/931#issuecomment-529693760. How did you overcome this? 

My os is MAC & grpc-tools v1.8.0.

**Comment by agreatfool** [comment]
Never mind. Just installed latest version of grpc-tools `v1.8.1`, seems it works ok.

**Comment by agreatfool** [comment]
Using new version of grpc-tools@1.8.1, and commands:

```
grpc_tools_node_protoc \
    --js_out=import_style=commonjs,binary:./src/proto \
    --grpc_out=generate_package_definition:./src/proto \
    --proto_path=./proto \
    proto/*.proto
```

Compare new generated codes with the old ones, difference of file `*_grpc_pb.js`:

```javascript
- var grpc = require('grpc');

- var BookServiceService = exports.BookServiceService = {
+ var BookServiceService = exports['com.book.BookService'] = {

- exports.BookServiceClient = grpc.makeGenericClientConstructor(BookServiceService);
```

**Comment by agreatfool** [comment]
Actually I knew this lib `grpc-js` for a long time. And seems eventually it starts it's stable version:

```
README.md | Bump grpc-js to 1.0 and stop calling it "beta" | 5 days ago
```

@smnbbrv Can I ask the purpose why do you using this lib `grpc-js` instead of using `grpc`? Is there any usecase that this lib is required instead of grpc?

**Comment by smnbbrv** [comment]
@agreatfool well, the main thing for me was that I can build a better docker image out of it and have a better CI:

- with the @grpc/grpc-js: with webpack I build the final js bundle which is approx. 2MB. Then I add it to docker image, let's say node:alpine and it's nearly not changed after I put those 2MB in
- with `grpc`: I can't run prebuild because C client is required, I should install deps inside docker to let gyp compile / pull the C client. That heavily increases the end size of the docker image and changes CI process in a way I don't want it to be.

I don't think switching to JS client from C client will be accompanied by some performance loss; in the end of the day I use it in browser and don't see any performance problems. Less infrastructure overhead vs. features I don't ever use in gRPC => the choice is quite an easy one :D

**Comment by agreatfool** [comment]
@smnbbrv Thank you, got the idea. I will have a look at how to implement an option to switch between grpc users & grpc-js users. At least there shall have no breaking changes that would affect existing users.

**Comment by smnbbrv** [comment]
I think adding `generate_package_definition` as an argument to ts_out is enough and should be meanwhile compliant / logical with the grpc-tools

```ts
protoc \
--plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
--ts_out=generate_package_definition:./your_dest_dir \
-I ./proto \
./your_proto_dir/*.proto
```

**Comment by agreatfool** [comment]
Version 3.0.0 has been published. Doc: [@grpc/grpc-js support](https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/master/doc/grpcjs_support.md).

**Comment by smnbbrv** [comment]
Well done! Thank you very much! Will give it a try asap

**Comment by miv** [comment]
Hello! I don't really get it how can it work as in examples? 

https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/master/examples/src/grpcjs/client.ts#L11

Here, bookGrpcPb does not have index signature and does not export this symbol. There should have been cast to `any` at least.

**Comment by miv** [comment]
No, the code is fine for JS. And everything works. 

But it should not compile in TS, at least with strict checks. Type of bookGrpcPb is of exports of ts module (this one `https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/master/examples/src/grpcjs/proto/book_grpc_pb.d.ts`), and it does not export "com.book.BookService". So i had to do a hack kind of like: 

`const BookServiceClient = grpc.makeClientConstructor((bookGrpcPb 
 as any)["com.book.BookService"], "BookService");`

(notice `any`)

Other than that everything work fine, thank you for your work :)

**Comment by agreatfool** [comment]
I have to say: Yes, it's ugly. Since the grpc team using name like "com.book.BookService", it cannot be well handled in typescript definition file. So you have to handle it using `any magic`.
