### ISSUE TITLE
Support grpc_js

### ISSUE THREAD

**Issue by zw-slime** [agreatfool/grpc_tools_node_protoc_ts#59]
Now grpc-tools [https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools] support @grpc/grpc-js , but this plugin can not support grpc_js

I change my code form grpc to grpc_js, according the following guide :
![image](https://user-images.githubusercontent.com/18528957/85516654-07e01480-b631-11ea-87cd-03725fae8d35.png)

The following is my code and generated code:

1. this is my sh file 
`${GRPC_TOOLS_NODE_PROTOC} \
      --js_out=import_style=commonjs,binary:"${f}" \
      --grpc_out=grpc_js:"${f}" \
      --plugin=protoc-gen-grpc="${GRPC_TOOLS_NODE_PROTOC_PLUGIN}" \
      -I "${f}" \
      "${f}"/*.proto`
2. generate js file
![image](https://user-images.githubusercontent.com/18528957/85516453-ca7b8700-b630-11ea-9e25-99f5ee97b958.png)
3. generate d.ts file
![image](https://user-images.githubusercontent.com/18528957/85516519-dd8e5700-b630-11ea-9f86-1415636cc830.png)

You can see ts file(2) is not consistency with js file(3).

**Comment by agreatfool** [comment]
Please read the doc, you shall use command `grpc_tools_node_protoc` with --grpc_out=**generate_package_definition**. In your example above, `generate_package_definition` was missed.

See example in the doc:
```
grpc_tools_node_protoc \
--js_out=import_style=commonjs,binary:./src/grpcjs/proto \
--grpc_out=generate_package_definition:./src/grpcjs/proto \
-I ./proto \
proto/*.proto
```

**Comment by zw-slime** [comment]
I change my code as you say.But I am sorry to say that the result is same. You can see ts file is not consistency with js file.

`${GRPC_TOOLS_NODE_PROTOC} \
      --js_out=import_style=commonjs,binary:"${f}" \
      --grpc_out=generate_package_definition:"${f}" \
      --plugin=protoc-gen-grpc="${GRPC_TOOLS_NODE_PROTOC_PLUGIN}" \
      -I "${f}" \
      "${f}"/*.proto`

![image](https://user-images.githubusercontent.com/18528957/85534109-a6757100-b643-11ea-896a-810de9c30e50.png)

![image](https://user-images.githubusercontent.com/18528957/85534177-b3926000-b643-11ea-89de-1038152e2674.png)

**Comment by agreatfool** [comment]
You need to do TWO steps to generate:

* js codes
*  ts definitions

see example in the root README.md:

```
# generate js codes via grpc-tools
grpc_tools_node_protoc \
--js_out=import_style=commonjs,binary:./your_dest_dir \
--grpc_out=./your_dest_dir \
--plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` \
-I ./proto \
./your_proto_dir/*.proto

# generate d.ts codes
protoc \
--plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
--ts_out=./your_dest_dir \
-I ./proto \
./your_proto_dir/*.proto
```

And I only saw you mentioned `grpc_out` plugin. Please make sure you have read through the root README doc & @grpc/grpc-js support doc.

**Comment by agreatfool** [comment]
I would close the issue for now, if you have any question, just reopen it.
