### ISSUE TITLE
Service typing doesn't work with @grpc/grpc-js

### ISSUE THREAD

**Issue by lone-cloud** [agreatfool/grpc_tools_node_protoc_ts#60]
You can see this problem in the grpc-js example of this project. To me this is a big regression from the grpc package. The problem seems to be that the client constructor returns a very generic ServiceClient type. I have not yet figured out how to make it specific.

<img width="365" alt="grpc-js-typing" src="https://user-images.githubusercontent.com/595980/86046103-7cd09700-ba01-11ea-9f9c-9f524b6742a1.png">

**Comment by agreatfool** [comment]
Got your idea. Let me explain the reason why.

### GRPC

In `grpc`, file `book_grpc_pb.js` generated by `grpc_tools_node_protoc`, contains:

```js
exports.BookServiceClient = grpc.makeGenericClientConstructor(BookServiceService);
```

So d.ts file this package could also generates the definition in file `book_grpc_pb.d.ts`:

```typescript
export class BookServiceClient extends grpc.Client implements IBookServiceClient {
  // ...
}
```

Then in `grpc` codes, there is the definition your codes could find.

------

### GRPC JS

In `grpcjs`, file `book_grpc_pb.js` generated by `grpc_tools_node_protoc` has no `BookServiceClient` exports. So this package also have to removed that definition accordingly.

User have to generate the client class manually:

```typescript
const BookServiceClient = grpc.makeClientConstructor(bookGrpcPb["com.book.BookService"], "BookService");
```

So the generated `BookServiceClient` has the type:

```typescript
export interface ServiceClient extends Client {
    [methodName: string]: Function;
}
```

As you can see, there is no detailed methods definitions.

-------

This change comes along with the change of the official `grpcjs` and `grpc_tools_node_protoc`, currently I have no idea how to help with it.

**Comment by agreatfool** [comment]
I would close the issue for now, if you have any question, just reopen it.

**Comment by lone-cloud** [comment]
Thanks for the detailed reply.

I'm using a near copy of your bash/build.sh to automate the generation of js/ts bindings. As hinted, I added a very hacky `echo "exports.BookServiceClient = grpc.makeGenericClientConstructor(BookServiceService);" >> ${PROTO_DEST}/<path to *grpc_pb.js>` to the build script to get the best of both worlds.

**Comment by lone-cloud** [comment]
I figured out the solution to my problem. In the context of the example: https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/master/examples/src/grpcjs/client.ts
To get proper typing with grpc-js you have to type the client like: `const client = new BookServiceClient("127.0.0.1:50051", grpc.credentials.createInsecure()) as unknown as bookGrpcPb .BookServiceClient;`

**Comment by agreatfool** [comment]
That's cool, thanks for the solution.

**Comment by agreatfool** [comment]
I have added this solution in the master branch: https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/70a3be35357b54438892c218c2b43b521d267fa6/examples/src/grpcjs/client.ts#L12

**Comment by ayZagen** [comment]
> In `grpcjs`, file `book_grpc_pb.js` generated by `grpc_tools_node_protoc` has no `BookServiceClient` exports. So this package also have to removed that definition accordingly.

@agreatfool I could see generated service in the file `book_grpc_pb.js`
```js
var BookService= exports.BookService= {
/// methods here ...
}
```

**Comment by agreatfool** [comment]
you are must using latest new version of grpc-tools https://www.npmjs.com/package/grpc-tools. And this session was talking about the old version.

**Comment by ayZagen** [comment]
indeed, but still service declarations are missing
