### ISSUE TITLE
Incorrect Server name generated

### ISSUE THREAD

**Issue by pierreis** [agreatfool/grpc_tools_node_protoc_ts#68]
With the following command:

```bash
protoc \
--plugin=protoc-gen-grpc=./node_modules/.bin/grpc_tools_node_protoc_plugin \
--plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
--js_out=import_style=commonjs,binary:. \
--grpc_out=generate_package_definition:. \
--ts_out=generate_package_definition:. \
--proto_path=. \
test.proto 
```

Proto file:

```protobuf
syntax = "proto3";

message EchoRequest {
    string message = 1;
}
  
message EchoResponse {
    string message = 1;
}
  
service Echo {
    rpc Echo(EchoRequest) returns (EchoResponse);
}
```

The generated JS file define the server as:

```js
var EchoService = exports['Echo'] = {
  echo: {
    [omitted]
  },
};
```

But the generated TS file sets:

```ts
export const EchoService: IEchoService;
```

There is consequently a mismatch between the generated JS and TS names, causing headaches when compiling the server.

Any pointers on what I could be doing wrong?

Thanks!

**Comment by agreatfool** [comment]
```typescript
export const BookServiceService: IBookServiceService;
```
is used in old grpc lib. Not for grpcjs.

Please see the difference between examples: `grpc/server.ts` vs `grpcjs/server.ts`.

`grpc/server.ts::startServer`
```typescript
server.addService(BookServiceService, new ServerImpl());
```

`grpcjs/server.ts::startServer`
```typescript
import * as bookGrpcPb from "./proto/book_grpc_pb";

server.addService(bookGrpcPb["com.book.BookService"], new ServerImpl());
```

**Comment by agreatfool** [comment]
About the changes of migrate to grpcjs, please read: [@grpc/grpc-js support](https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/master/doc/grpcjs_support.md). Please reopen this, if you have further issues.
