### ISSUE TITLE
Support for Any.pack

### ISSUE THREAD

**Issue by long1eu** [agreatfool/grpc_tools_node_protoc_ts#72]
Hi! 

Tha google.protobuf.Any type has a pack and unpack method. If is possible to added them? These are the js definitions.

```
/**
 * Packs the given message instance into this Any.
 * For binary format usage only.
 * @param {!Uint8Array} serialized The serialized data to pack.
 * @param {string} name The type name of this message object.
 * @param {string=} opt_typeUrlPrefix the type URL prefix.
 */
proto.google.protobuf.Any.prototype.pack = function(serialized, name,
                                                    opt_typeUrlPrefix) {
  if (!opt_typeUrlPrefix) {
    opt_typeUrlPrefix = 'type.googleapis.com/';
  }

  if (opt_typeUrlPrefix.substr(-1) != '/') {
    this.setTypeUrl(opt_typeUrlPrefix + '/' + name);
  } else {
    this.setTypeUrl(opt_typeUrlPrefix + name);
  }

  this.setValue(serialized);
};


/**
 * @template T
 * Unpacks this Any into the given message object.
 * @param {function(Uint8Array):T} deserialize Function that will deserialize
 *     the binary data properly.
 * @param {string} name The expected type name of this message object.
 * @return {?T} If the name matched the expected name, returns the deserialized
 *     object, otherwise returns null.
 */
proto.google.protobuf.Any.prototype.unpack = function(deserialize, name) {
  if (this.getTypeName() == name) {
    return deserialize(this.getValue_asU8());
  } else {
    return null;
  }
};
```

**Comment by agreatfool** [comment]
Hi @long1eu,

I have made some test.

1. git clone git@github.com:agreatfool/grpc_tools_node_protoc_ts.git
2. cd grpc_tools_node_protoc_ts/examples
3. add file `examples/proto/goolge/protobuf/any.proto`, source comes from [here](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/any.proto)
![anyproto](https://user-images.githubusercontent.com/195293/96218106-9ac50600-0fb6-11eb-82f7-0ee3a9ff9410.png)
4. edit book.proto file, add `import "google/protobuf/any.proto";` and:
![anymessage](https://user-images.githubusercontent.com/195293/96218168-c7791d80-0fb6-11eb-9d55-96d1098d6a41.png)
5. run `examples/bash/build.sh`, see what changed in file: `examples/src/grpc/proto/book_pb.js`

There is no `pack` & `unpack` generated.
![nopack](https://user-images.githubusercontent.com/195293/96218404-42423880-0fb7-11eb-9089-dc9a749ae296.png)

And js codes generated come from [grpc-tools](https://www.npmjs.com/package/grpc-tools). You'd better ask them about this.

**Comment by long1eu** [comment]
Hey!

Thanks for this. As you can see the pack and unpack functions just combines the two already existing method. Good to know that this is not a ts issue. Thanks again.
