### ISSUE TITLE
Also generates property accessors, not just getters / setters

### ISSUE THREAD

**Issue by entropitor** [agreatfool/grpc_tools_node_protoc_ts#75]
The tutorials for grpc are not using getters / setters (https://grpc.io/docs/languages/node/basics/), is this a mistake? 

Or why does this tool not generate typescript bindings for these? 

so we can do `request.call.myField` instead of `request.call.getMyField()`

**Comment by agreatfool** [comment]
Hi @entropitor,

I think you could submit your issue here: [grpc-node/issues](https://github.com/grpc/grpc-node/issues). Since it's the issue of the design of grpc. I could hardly help.

Best Regards

**Comment by entropitor** [comment]
@agreatfool But the [docs of grpc-node](https://grpc.io/docs/languages/node/quickstart/) show e.g. this example

```javascript
function sayHello(call, callback) {
  callback(null, {message: 'Hello ' + call.request.name});
}

function sayHelloAgain(call, callback) {
  callback(null, {message: 'Hello again, ' + call.request.name});
}

function main() {
  var server = new grpc.Server();
  server.addService(hello_proto.Greeter.service,
                         {sayHello: sayHello, sayHelloAgain: sayHelloAgain});
  server.bind('0.0.0.0:50051', grpc.ServerCredentials.createInsecure());
  server.start();
}

```

while the typescript bindings would require `call.request.getName()`, why not type both, given the library seems to allow it?

**Comment by agreatfool** [comment]
hmmm, interesting. I haven't noticed that, let me have a look.

**Comment by agreatfool** [comment]
I just read through the generated js codes. And found no `getter/setter` functions. Only functions `getXXX/setXXX`.

Please have a look at: https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/bceebf472e8c74cc8b100f5ad625e108d0d9c496/examples/src/grpc/proto/book_pb.js#L723-L738

And typescript bindings are corresponding to the js source code. I can't add any signature while they are not in the code.

I still suggest you could submit an issue in official grpc-node repo.

**Comment by entropitor** [comment]
Hmm, it seems to stem from https://github.com/grpc/grpc/tree/v1.33.1/examples/node/dynamic_codegen versus https://github.com/grpc/grpc/tree/v1.33.1/examples/node/static_codegen

**Comment by agreatfool** [comment]
Read the readme of dynamic_codegen:

> This is the dynamic code generation variant of the Node examples. Code in these examples is generated at runtime using Protobuf.js.

`generated at runtime`

So example code here are not using [grpc_tools_node_protoc](https://www.npmjs.com/package/grpc-tools). Thus, also not using d.ts files from current tool.

**Comment by entropitor** [comment]
Yes, you are right. What I want is https://github.com/grpc/grpc-node/pull/1474 I guess

Thank you for your help!
