### ISSUE TITLE
Typescript-javascript enum incompatible

### ISSUE THREAD

**Issue by steeni** [agreatfool/grpc_tools_node_protoc_ts#76]
Hi,

Generated enum types do not work in typescript as they should. Here is simplified version of what I had in proto:
```
message Foo {
    enum Type {
        ONE = 0;
        TWO = 1;
    }

    Type type = 1;
    // .. other fields..
}
```

I have generated .d.ts and .js files from the above. In typescript I want to get a string of the enum (for persistence). This can be done in typescript normally like this `Type[Type.ONE]` -> "ONE", but now it gives undefined. I worked around it with the helper function like this:
```
function getEnumLabel(obj: any, value: any) {
    return Object.keys(obj).find(key => obj[key] === value);
}
```

I would rather use the normal typescript way to access the label, but I think the runtime javascript is not compatible with that. Can that be fixed or am I possibly doing something wrong?

package.json
```
"grpc-tools": "^1.9.1",
"grpc_tools_node_protoc_ts": "^5.0.1"
```

code generation command that I used
```
npx grpc_tools_node_protoc \
    --js_out=import_style=commonjs,binary:${PROTO_DEST} \
    --grpc_out=grpc_js:${PROTO_DEST} \
    -I ../shared/proto \
    ../shared/proto/*.proto

npx grpc_tools_node_protoc \
    --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
    --ts_out=grpc_js:${PROTO_DEST} \
    -I ../shared/proto \
    ../shared/proto/*.proto
```

**Comment by agreatfool** [comment]
Hi @steeni , could you please provide the minimal codes that can reproduce your issue. Including: *.proto, generated *.js, and generated *.d.ts. Also your app codes, like you mentioned: `Type[Type.ONE] -> "ONE"`. Currently I cannot catch your point.

Sorry for the late reply.

Best Regards
