### ISSUE TITLE
Argument of type 'Handler' is not assignable to parameter of type 'UntypedServiceImplementation'

### ISSUE THREAD

**Issue by yellowandy** [agreatfool/grpc_tools_node_protoc_ts#79]
Upgraded to the latest and started getting the error message above when using the addService call.  Noticed that in your example you are ignoring the compilation issue with the ts-ignore directive, is this a known issue?

https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/b85f1440a357a2f4a935d14dfd78072a7dcbfb10/examples/src/grpcjs/server.ts#L75

**Comment by agreatfool** [comment]
Do you mean this one? https://github.com/agreatfool/grpc_tools_node_protoc_ts/issues/60

**Comment by agreatfool** [comment]
Seems not, could you share some sample codes or proto file?

**Comment by agreatfool** [comment]
Yes, it's a known issue. Let me have a look what I can do to solve | improve it.

**Comment by agreatfool** [comment]
New version v5.1.0 has been published. Closing.

**Comment by badsyntax** [comment]
@agreatfool can you link the code changes to this issue?

**Comment by agreatfool** [comment]
@badsyntax https://github.com/agreatfool/grpc_tools_node_protoc_ts/commit/a2e4dfa738351541a1e74603c18c8525a9ec9d14

**Comment by badsyntax** [comment]
Thanks. Great to see this fixed. It looks like we now have Type parity across the popular tools:

- grpc-proto-loader
- ts-protoc-gen
- grpc_tools_node_protoc_ts

I'll update my example in https://github.com/badsyntax/grpc-js-types to show this latest change.

**Comment by codedread** [comment]
I started getting TS compilation errors due to this change.  VS Code expects the following to be in my implementation:

```typescript
class MyServerImpl implements IMyServiceServer {
    [name: string]: grpc.UntypedHandleCall; // <== This line is expected...

    // But if I have properties / methods that are not RPC-handling like...
    data: Foo = ...;
    someOtherFunction() {...}
}
```

I get the following compiler error:  Property 'data' of type 'DataService' is not assignable to string index type 'HandleCall<any, any>'.ts(2411)

**Comment by agreatfool** [comment]
@codedread I did't expect the case of private attributes of the implementation class. Seems this breaking change affected a lot. I will have a check with it, maybe revert this.

Fixing one issue and introduce another is not good. Sorry for the inconvenience.

**Comment by agreatfool** [comment]
New version `v5.1.1` has been published, only some docs added.

I recommend the `Object style` implementation of server side:

```typescript
const Impl: IBookServiceServer = {
    getBook: (call: grpc.ServerUnaryCall<GetBookRequest, Book>, callback: sendUnaryData<Book>): void => {},

    getBooks: (call: grpc.ServerDuplexStream<GetBookRequest, Book>): void => {},

    getBooksViaAuthor: (call: grpc.ServerWritableStream<GetBookViaAuthor, Book>): void => {},

    getGreatestBook: (call: grpc.ServerReadableStream<GetBookRequest, Book>, callback: sendUnaryData<Book>): void => {},
};

const server = new grpc.Server();
server.addService(BookServiceService, Impl);
```

Read more [here](https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/master/doc/server_impl_signature.md).

**Comment by badsyntax** [comment]
I think this is the right approach. While no-one likes `UntypedServiceImplementation`, it unfortunately cannot be changed now to keep backwards compatibility. I did some research to see if we can adjust the types in a generic/non-breaking way to support class implementations, but wasn't able to find a solution. There's been some discussion about this here: https://github.com/grpc/grpc-node/pull/1474#discussion_r496861800

**Comment by agreatfool** [comment]
@badsyntax That's pretty cool. Thanks for the sharing.

**Comment by codedread** [comment]
Sadly, not supporting the class syntax means at least two not-great things:

  * there is no "instance" of the service so testing becomes more complicated as you have to carefully clear out state of the service.
  * there is no constructor step which I can use as a convenient spot for dependency injection or to mock out dependencies in unit tests

Yes, I can work around this but it is not great.  My current TypeScript:

```
import { Logger} from 'logger';
class MyServer {
  logger: Logger;
  constructor() {
    this.logger = new Logger();
  }
  // rest of GRPC things here...
}
```

In my test, I want to mock out Logger as a dependency:

```
import { * as loggerModule } from 'logger';
describe('', () => {
  const myService: MyService;
  beforeEach(() => {
    importMock.mockClassInPlace(commonModule, 'Logger');
    myService = new MyService(); // Each test gets a new instance of a service...
  });
  // All my tests here that don't have to worry about the Logger dependency...
}
```

**Comment by agreatfool** [comment]
Currently it seems this is the only possible way to do even from official comments : https://github.com/grpc/grpc-node/pull/1474#discussion_r496907495.

For class style, maybe we can make something like this (idea, not tested):

```typescript
class ServiceWrapper {
  // class attributes & other stuff
  // ...

  public svcImpl: IBookServiceServer = {
    getBook: (call: grpc.ServerUnaryCall<GetBookRequest, Book>, callback: sendUnaryData<Book>): void => {},
    getBooks: (call: grpc.ServerDuplexStream<GetBookRequest, Book>): void => {},
    getBooksViaAuthor: (call: grpc.ServerWritableStream<GetBookViaAuthor, Book>): void => {},
    getGreatestBook: (call: grpc.ServerReadableStream<GetBookRequest, Book>, callback: sendUnaryData<Book>): void => {},
  };
}

const impl = new ServiceWrapper().svcImpl;
const server = new grpc.Server();
server.addService(BookServiceService, impl);
```

**Comment by jahewson** [comment]
Hi everyone, I hit the same issue with the typings for `addService`. I'm thinking that a backwards compatible fix would be to generate an additional interface type without `UntypedServiceImplementation`, e.g.

```typescript
export interface ITypedGreeterServer {
  sayHello: grpc.handleUnaryCall<protos_greeter_pb.HelloRequest, protos_greeter_pb.HelloReply>;
}

export interface IGreeterServer extends ITypedGreeterServer, grpc.UntypedServiceImplementation {
}
```

This would allow `ITypedGreeterServer` to be implemented in a class.

Backwards-compatible type-safe `addService` could be achieved with an override:

```typescript
addService(service: ServiceDefinition, implementation: UntypedServiceImplementation): void;
addService<TypedServiceImplementation extends Record<any,any>>(service: ServiceDefinition, implementation: TypedServiceImplementation): void;
```

```typescript
class GreeterServiceImpl implements services.ITypedGreeterServer {
   ...
}

const impl = new GreeterServiceImpl();
server.addService<services.ITypedGreeterServer>(services.GreeterService, impl);
```

and everything else should just keep working.

---

**Alternatively**, if you want to get `ITypedGreeterServer` **today**, you can use [this helper](https://stackoverflow.com/a/51956054) in your own code:

```typescript
type KnownKeys<T> = {
  [K in keyof T]: string extends K ? never : number extends K ? never : K
} extends { [_ in keyof T]: infer U } ? U : never;

type KnownOnly<T extends Record<any,any>> = Pick<T, KnownKeys<T>>;
```

Which gets you:

```typescript
type ITypedGreeterServer = KnownOnly<services.IGreeterServer>;
```

**Comment by paymog** [comment]
@jahewson is any chance you have a more complete example you can share with the generic magic you're suggesting?
