### ISSUE TITLE
Generate service server interface

### ISSUE THREAD

**Issue by derolf** [agreatfool/grpc_tools_node_protoc_ts#8]
It would be nice to have an interface for the server side of services with strongly typed function signatures.

A service developer can then implement that interface and pass it as a method map to gRPC addService.

**Comment by agreatfool** [comment]
Please read [codes](https://github.com/agreatfool/SASDN-Sample/blob/master/src/services/register.ts) to have an example.

Maybe also you need: [SASDN](https://github.com/agreatfool/SASDN/blob/master/src/lib/rpc/App.ts).

**Comment by derolf** [comment]
Creating manual wrappers is the way I do it right now as well.

What I mean is that it would be nice to not have to do that. These wrappers could be auto generated...

**Comment by agreatfool** [comment]
Yeah, it's great to reduce the codes of manual works. 

What I think is: Current repo is just the typescript explaination of [grpc_tools_node_protoc](https://www.npmjs.com/package/grpc-tools), prefer adding no additional functionality in it. If I need any more functionality, I would like to make a wrapper framework like [SASDN](https://github.com/agreatfool/SASDN) to help.
