### ISSUE TITLE
Pass Object to gRPC

### ISSUE THREAD

**Issue by tradical-allstripes** [agreatfool/grpc_tools_node_protoc_ts#80]
Hey! Love the project! If this is infeasible or there's some reason not to do it, just let me know, but here's some functionality I would really love to see:

Something really useful would be to be able to hand an object off to gRPC (```call.write```, for example), like you can in raw JS. Just from what I know so far, I think this would be a great use case for ```AsObject``` that you guys have that can be used when receiving protos. AFAICT all that would be involved would be two things:

* Changing the definition of the methods to accept a real proto or an ```AsObject```
* Writing a converter in the gRPC stub

I admit the latter seems like it could be a challenge. What do you think? Is this worth doing?

**Comment by agreatfool** [comment]
@tradical-allstripes  Could you please give some simple example about what you want? Maybe js codes is enough. Currently I cannot get the point of your requirement.

**Comment by tradical-allstripes** [comment]
Hey! Thanks for the reply!

What do you mean JS codes?

Here's what we're doing now:

```ts
const fooMessage = new FooMessage()
const innerMessage = new InnerMessage()

innerMessage.setData("foo")
fooMessage.setMessage(innerMessage)
```

Here's how I want it to be:

```ts
call.write({ message: { data: "foo" } } as FooMessage.AsObject)
```

or something like that.

Alternatively, we could do a builder, like protos use in Java:

```ts
call.write(
  FooMessage.builder().innerMessage(
    InnerMessage.builder().setData("foo").build())
  .build())
```

With one of these two solutions, we can program declaratively instead of imperatively; plus it just looks nicer. I figured the first one would be easier, but I could be wrong.

**Comment by agreatfool** [comment]
Sorry for the late reply. Got a car accident last week.

As you may know this repo is used to generating typescript signature according to the javascript codes generated by `grpc-tools`. So I cannot make some new methods like the builder you mentioned.

What the typescript signatures you are using are all exactly consistent with the javascript codes. Official grpc node static code-gen usage could be found here: [static_codegen/route_guid](https://github.com/grpc/grpc/tree/v1.34.1/examples/node/static_codegen/route_guide). As I know so far, seems there is no such usage you mentioned.

If you really want this kind of grammar/statement. You can raise an issue here: [grpc/grpc-node/issues](https://github.com/grpc/grpc-node/issues).

**Comment by tradical-allstripes** [comment]
Oh yeah I see what you mean. Somehow I imagined the problem was on the TypeScript side, but I see how JS is needed too. If they implement it on the JS side, do you think your project will convert that to TypeScript properly without further modification?

**Comment by agreatfool** [comment]
No. I don't think so. The target of this repo/tool is to create signature accordingly to help the development of grpc node services. All the works are focus on the consistency to the js codes.

**Comment by tradical-allstripes** [comment]
Ok I will look into changing this on the ```grpc-node``` side.
