### ISSUE TITLE
handlebars-helpers doesn't seem to be maintained any longer 

### ISSUE THREAD

**Issue by danias** [agreatfool/grpc_tools_node_protoc_ts#81]
One of the project dependencies, **handlebars-helpers**, doesn't seem to be active any more. One of its dependencies managed by the same organisation, **helper-markdown** uses an old version of highlight.js which has a DoS vulnerability. As a result, all projects using grpc_tools_node_protoc_ts get a moderate severity alert and some cannot merge. 

Can this be replaced with some other package to avoid this and further problems in the future?

https://github.com/highlightjs/highlight.js/blob/master/SECURITY.md

![image](https://user-images.githubusercontent.com/1571105/105610512-929c1400-5db8-11eb-8153-376caa860335.png)
![image](https://user-images.githubusercontent.com/1571105/105610526-a6e01100-5db8-11eb-9e0a-0ceb5dc97fd0.png)

**Comment by agreatfool** [comment]
Actually no worries about the vulnerability. Codes run with your app are from `javascript codes generated by grpc-tools`. 

This tool is just generating the typescript signatures to help your development.

See the doc: https://github.com/agreatfool/grpc_tools_node_protoc_ts#about-vulnerability

Anyway the vulnerability is exactly annoying. I will try to replace these libs with self made strings, in later version.

Thank you for the reporting.

**Comment by mkorpela** [comment]
So could this be replaced soon?

```
└─┬ grpc_tools_node_protoc_ts@5.1.3
  └─┬ handlebars-helpers@0.10.0
    └─┬ helper-markdown@1.0.0
      └── highlight.js@9.18.5
```

```
> node deprecated.js

-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

  Verion 9 of Highlight.js has reached EOL.  It will no longer
  be supported or receive security updates in the future.
  Please upgrade to version 10 or encourage your indirect
  dependencies to do so.

  For more info:
  
  https://github.com/highlightjs/highlight.js/issues/2877
  https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_UPGRADE.md
 
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
```

**Comment by agreatfool** [comment]
Removed `handlebars-helpers` in `v5.2.1`, closing
