### ISSUE TITLE
Issue with repeated float

### ISSUE THREAD

**Issue by konstantinblaesi** [agreatfool/grpc_tools_node_protoc_ts#85]
Hi,
thanks for the great library, I enjoy having auto completion and type safety :)
My client fails to read the response if it includes a repeated float field. [Example to reproduce and details here](https://github.com/konstantinblaesi/grpc-issue).
```
> ts-node src/client.ts

Calling DemoClient.doDemo
Error: 13 INTERNAL: Response message parsing error: reader.isDelimited is not a function
    at Object.callErrorFromStatus (/home/konstantin/Documents/Projects/grpc-issue/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/home/konstantin/Documents/Projects/grpc-issue/node_modules/@grpc/grpc-js/src/client.ts:334:36)
    at Object.onReceiveStatus (/home/konstantin/Documents/Projects/grpc-issue/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
    at Object.onReceiveStatus (/home/konstantin/Documents/Projects/grpc-issue/node_modules/@grpc/grpc-js/src/client-interceptors.ts:387:48)
    at /home/konstantin/Documents/Projects/grpc-issue/node_modules/@grpc/grpc-js/src/call-stream.ts:249:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 13,
  details: 'Response message parsing error: reader.isDelimited is not a function',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```
Am I doing something wrong or is this just a bug in the grpc core?

**Comment by konstantinblaesi** [comment]
The root cause seems to be the google-protobuf version pulled in by this library, can you look into it ? See https://github.com/grpc/grpc-node/issues/1691

**Comment by agreatfool** [comment]
As your issue https://github.com/grpc/grpc-node/issues/1691 mentioned, seems `google-protobuf` is required to run the grpc codes.

Errors gone after:

```bash
$ npm install google-protobuf -S
```

Verified. I'll close for now. If any further issues, just reopen it. Thanks.

**Comment by konstantinblaesi** [comment]
Does this mean that there is some bug in google-protobuf@3.12.4 since your library already pulled that in ?

**Comment by agreatfool** [comment]
You can have a look at the generated js codes: https://github.com/konstantinblaesi/grpc-issue/blob/a4da754e07dbe5a5b56d502856871bdd37b59034/src/proto/code/service_pb.js#L13. 

It requires lib `google-protobuf` in the runtime. So if you run the app without this lib, error happened.

**Comment by agreatfool** [comment]
If you are asking why `google-protobuf` here: https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/d1e72428e69acd971beca7d89c347f87c86e01c4/package.json#L31.

Because some parsing scripts in the tool need it: https://github.com/agreatfool/grpc_tools_node_protoc_ts/blob/8bdd531a68c0bdb9319d0a23dcad193701962e0d/src/lib/ExportMap.ts#L7

**Comment by konstantinblaesi** [comment]
Thanks for clarifying. I guess I had dependency resolution wrong in my mind assuming `require("google-protobuf")` could be resolved to my `grpc-issue/node_modules/grpc_tools_node_protoc_ts/node_modules/google-protobuf`
Running a test.js with `require("google-protobuf")` I get
> Error: Cannot find module 'google-protobuf'
But I never saw such errors when running the typescript variant, so that was tricking me to think it could resolve the dependency :D

**Comment by Connor-Wallace** [comment]
Is there a reason that the google-protobuf version cannot be upgraded to 3.14.0 or later for grpc_tools_node_protoc_ts? There's been a few updates since the current required version that fix bugs related to checking packed repeated fields.
