### ISSUE TITLE
Support 'optional' fields in proto3

### ISSUE THREAD

**Issue by mingrammer** [agreatfool/grpc_tools_node_protoc_ts#88]
Since [protoc@v3.15.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0), it started to support `optional` field. It would be nice if the `protoc-gen-ts` plugin supports it. Could you please work on it? Thanks.

Here is the [reference](https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md) about how to implement.

**Comment by LeeStephen** [comment]
This would be greatly appreciated.

**Comment by isbang** [comment]
+1

**Comment by huan** [comment]
I need this beautiful new feature, now it's a block from my project https://github.com/wechaty/grpc/issues/109

**Comment by wespen** [comment]
+1

**Comment by firelizzard18** [comment]
I've opened #97 to solve this. If you want to use my repo directly:

```
% yarn add -D firelizzard18/grpc_tools_node_protoc_ts#feature/proto3-optional
```
or

```
% npm install -D firelizzard18/grpc_tools_node_protoc_ts#feature/proto3-optional
```

**Comment by agreatfool** [comment]
@firelizzard18 cool, will check in weekend, thanks

**Comment by antonphilin** [comment]
+1

**Comment by agreatfool** [comment]
v5.2.0 released
